<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>run.endive.cm</groupId>
    <artifactId>endive-cm</artifactId>
    <version>999-SNAPSHOT</version>
  </parent>
  <artifactId>validator</artifactId>
  <packaging>jar</packaging>

  <name>Endive CM - Component Validator</name>
  <description>Validation of Component Model binaries, over and above what wasm-tools checks</description>

  <dependencies>
    <dependency>
      <groupId>run.endive.cm</groupId>
      <artifactId>parser</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive.cm</groupId>
      <artifactId>types</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive.cm</groupId>
      <artifactId>wasm-tools</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>16</source>
          <target>16</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
