package run.endive.cm.bindgen.it.helloworld;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import run.endive.cm.bindgen.it.Components;
import run.endive.cm.runtime.Bindgen;
import run.endive.cm.runtime.ComponentStore;
import run.endive.cm.types.WasmComponent;
import run.endive.runtime.TrapException;

/**
 * The whole route, from WIT to a running call.
 *
 * <p>The bindings this calls are generated by the processor from the same WIT the component is
 * built against, so nothing here is written by hand twice. {@code greet} traps unless the host's
 * string reaches guest memory intact, which is what makes this prove the value crossed rather than
 * only that a call was made.
 */
@Bindgen(world = "hello-world")
public class HelloWorldTest {

    private static WasmComponent component;

    /** Built the way a test fixture is built, from a core module and the world it implements. */
    @BeforeAll
    static void buildComponent() {
        component =
                Components.build(
                        Components.bytes("/hello-world.wat"),
                        Components.text("/wit/hello-world.wit"),
                        "hello-world");
    }

    @Test
    void theGeneratedBindingsInstantiateTheComponent() {
        HelloWorld bindings = instantiate(() -> "world");

        assertNotNull(bindings.instance());
        assertEquals(Set.of("greet"), bindings.instance().exportNames());
    }

    @Test
    void callingAnExportEntersTheGuest() {
        boolean[] called = {false};

        HelloWorld bindings =
                instantiate(
                        () -> {
                            called[0] = true;
                            return "world";
                        });
        bindings.greet();

        assertTrue(called[0], "expected the guest to call back into the host import");
    }

    /**
     * The guest checks what it was handed, so a different string traps. Without this the check
     * above would pass on a host import whose value never arrived.
     */
    @Test
    void aStringTheGuestDoesNotExpectTraps() {
        HelloWorld bindings = instantiate(() -> "mars");

        assertThrows(TrapException.class, bindings::greet);
    }

    private static HelloWorld instantiate(HelloWorld.Imports imports) {
        return HelloWorld.instantiate(new ComponentStore(), component, imports);
    }
}
