package run.endive.cm.bindgen.it.helloworld;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import run.endive.cm.parser.ComponentParser;
import run.endive.cm.runtime.Bindgen;
import run.endive.cm.runtime.ComponentStore;
import run.endive.cm.tools.ComponentEmbed;
import run.endive.cm.tools.ComponentNew;
import run.endive.cm.tools.ComponentValidate;
import run.endive.cm.types.WasmComponent;
import run.endive.runtime.TrapException;

/**
 * The whole route, from WIT to a running call.
 *
 * <p>The bindings this calls are generated by the processor from the same WIT the component is
 * built against, so nothing here is written by hand twice. {@code greet} traps unless the host's
 * string reaches guest memory intact, which is what makes this prove the value crossed rather than
 * only that a call was made.
 */
@Bindgen(world = "hello-world")
public class HelloWorldTest {

    private static WasmComponent component;

    /** Built the way a test fixture is built, from a core module and the world it implements. */
    @BeforeAll
    static void buildComponent() {
        byte[] embedded =
                ComponentEmbed.embed(resource("/hello-world.wat"), text("/wit/hello-world.wit"));
        byte[] binary = ComponentNew.create(embedded);

        ComponentValidate.validate(new ByteArrayInputStream(binary), "component-model");
        component =
                ComponentParser.builder()
                        .withValidation(false)
                        .build()
                        .parse(() -> new ByteArrayInputStream(binary));
    }

    @Test
    void theGeneratedBindingsInstantiateTheComponent() {
        HelloWorld bindings = instantiate(() -> "world");

        assertNotNull(bindings.instance());
        assertEquals(Set.of("greet"), bindings.instance().exportNames());
    }

    @Test
    void callingAnExportEntersTheGuest() {
        boolean[] called = {false};

        HelloWorld bindings =
                instantiate(
                        () -> {
                            called[0] = true;
                            return "world";
                        });
        bindings.greet();

        assertTrue(called[0], "expected the guest to call back into the host import");
    }

    /**
     * The guest checks what it was handed, so a different string traps. Without this the check
     * above would pass on a host import whose value never arrived.
     */
    @Test
    void aStringTheGuestDoesNotExpectTraps() {
        HelloWorld bindings = instantiate(() -> "mars");

        assertThrows(TrapException.class, bindings::greet);
    }

    private static HelloWorld instantiate(HelloWorld.Imports imports) {
        return HelloWorld.instantiate(new ComponentStore(), component, imports);
    }

    private static String text(String path) {
        return new String(resource(path), StandardCharsets.UTF_8);
    }

    private static byte[] resource(String path) {
        try (InputStream is = HelloWorldTest.class.getResourceAsStream(path)) {
            assertNotNull(is, "resource not found: " + path);
            return is.readAllBytes();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
